# Generated by Django 3.2.23 on 2024-03-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0003_rename_vend_place_of_supply_recurring_bills_vend_source_of_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_bills',
            name='cust_billing_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
