# Generated by Django 3.2.23 on 2024-03-30 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0004_recurring_bills_cust_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_bills',
            name='bank_acc_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recurring_bills',
            name='bank_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.banking'),
        ),
        migrations.AddField(
            model_name='recurring_bills',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recurring_bills',
            name='check_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recurring_bills',
            name='upi_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
