# Generated by Django 3.2.23 on 2024-03-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0005_auto_20240330_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurring_bills',
            name='bank_acc_no',
        ),
        migrations.RemoveField(
            model_name='recurring_bills',
            name='bank_name',
        ),
    ]
