# Generated by Django 3.2.23 on 2024-03-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0006_auto_20240330_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_bills',
            name='igst',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
