# Generated by Django 3.2.23 on 2024-03-30 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0007_recurring_bills_igst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurring_bills',
            old_name='text_amount',
            new_name='tax_amount',
        ),
    ]
