# Generated by Django 3.2.23 on 2024-02-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0007_pricelist_pricelistcomment_pricelistitem_pricelisttransactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistcomment',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
