# Generated by Django 3.2.23 on 2024-02-08 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0016_company_payment_term'),
        ('Company_Staff', '0008_alter_pricelistcomment_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('vendor_display_name', models.CharField(default='', max_length=255)),
                ('vendor_email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(default='', max_length=15)),
                ('phone', models.CharField(default='', max_length=15)),
                ('company_name', models.CharField(default='', max_length=255)),
                ('skype_name_number', models.CharField(default='', max_length=255)),
                ('designation', models.CharField(default='', max_length=255)),
                ('department', models.CharField(default='', max_length=255)),
                ('website', models.URLField(blank=True, default='', null=True)),
                ('gst_treatment', models.CharField(default='', max_length=255)),
                ('gst_number', models.CharField(default='', max_length=20)),
                ('pan_number', models.CharField(default='', max_length=20)),
                ('currency', models.CharField(default='', max_length=3)),
                ('opening_balance_type', models.CharField(default='', max_length=255)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('source_of_supply', models.CharField(default='', max_length=255)),
                ('billing_attention', models.CharField(default='', max_length=255)),
                ('billing_address', models.TextField()),
                ('billing_city', models.CharField(default='', max_length=255)),
                ('billing_state', models.CharField(default='', max_length=255)),
                ('billing_country', models.CharField(default='', max_length=255)),
                ('billing_pin_code', models.CharField(default='', max_length=10)),
                ('billing_phone', models.CharField(default='', max_length=15)),
                ('billing_fax', models.CharField(default='', max_length=15)),
                ('shipping_attention', models.CharField(default='', max_length=255)),
                ('shipping_address', models.TextField()),
                ('shipping_city', models.CharField(default='', max_length=255)),
                ('shipping_state', models.CharField(default='', max_length=255)),
                ('shipping_country', models.CharField(default='', max_length=255)),
                ('shipping_pin_code', models.CharField(default='', max_length=10)),
                ('shipping_phone', models.CharField(default='', max_length=15)),
                ('shipping_fax', models.CharField(default='', max_length=15)),
                ('remarks', models.TextField()),
                ('vendor_status', models.CharField(default='', max_length=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Register_Login.company_payment_term')),
            ],
        ),
        migrations.CreateModel(
            name='VendorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('login_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('work_phone', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('skype_name_number', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_remarks_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_mail_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_from', models.TextField(max_length=300)),
                ('mail_to', models.TextField(max_length=300)),
                ('subject', models.TextField(max_length=250)),
                ('content', models.TextField(max_length=900)),
                ('mail_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_doc_upload_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('document', models.FileField(upload_to='doc/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('login_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_comments_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('login_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.vendor')),
            ],
        ),
    ]
