# Generated by Django 3.2.23 on 2024-04-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0009_auto_20240401_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurring_bills',
            old_name='repeat_every',
            new_name='credit_period_termname',
        ),
        migrations.AddField(
            model_name='recurring_bills',
            name='credit_period_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurring_bills',
            name='repeat_every_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurring_bills',
            name='repeat_every_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
