# Generated by Django 3.2.23 on 2024-02-14 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0016_company_payment_term'),
        ('Company_Staff', '0010_auto_20240214_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRepeatEvery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat_every', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('repeat_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('duration', models.IntegerField(default=0, null=True)),
                ('days', models.IntegerField(default=0, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
            ],
        ),
    ]
