# Generated by Django 3.2.23 on 2024-04-03 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0011_auto_20240402_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurritemslist',
            name='text',
        ),
        migrations.AddField(
            model_name='recurring_bills',
            name='item_list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.items'),
        ),
        migrations.AddField(
            model_name='recurritemslist',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.items'),
        ),
        migrations.AddField(
            model_name='recurritemslist',
            name='taxGST',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recurritemslist',
            name='taxIGST',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
