# Generated by Django 3.2.23 on 2024-02-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0011_companyrepeatevery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
