# Generated by Django 3.2.23 on 2024-04-03 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0012_auto_20240403_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurring_bills',
            name='item_list_id',
        ),
        migrations.AddField(
            model_name='recurritemslist',
            name='recurr_bill_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.recurring_bills'),
        ),
    ]
