# Generated by Django 3.2.23 on 2024-02-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
        ('Company_Staff', '0013_auto_20240223_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.IntegerField(blank=True, default=0, null=True)),
                ('salary_date', models.DateField(null=True)),
                ('casual_leave', models.IntegerField(blank=True, default=0, null=True)),
                ('month', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, default=0, null=True)),
                ('basic_salary', models.IntegerField(blank=True, default=0, null=True)),
                ('conveyance_allowance', models.IntegerField(blank=True, default=0, null=True)),
                ('hra', models.IntegerField(blank=True, default=0, null=True)),
                ('other_allowance', models.IntegerField(blank=True, default=0, null=True)),
                ('total_working_days', models.IntegerField(blank=True, default=0, null=True)),
                ('other_cuttings', models.IntegerField(blank=True, default=0, null=True)),
                ('add_bonus', models.IntegerField(blank=True, default=0, null=True)),
                ('salary', models.FloatField(blank=True, default=0, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='Active', max_length=100, null=True)),
                ('DraftorSave', models.CharField(max_length=100, null=True)),
                ('total_amount', models.FloatField(blank=True, default=0, null=True)),
                ('attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.attendance')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.payroll_employee')),
            ],
        ),
        migrations.CreateModel(
            name='HistorySalaryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('action', models.CharField(choices=[('add', 'Add'), ('edit', 'Edit')], default='add', max_length=7)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('login_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
                ('salary_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.salarydetails')),
            ],
        ),
        migrations.CreateModel(
            name='CommentSalaryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.payroll_employee')),
                ('salary_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.salarydetails')),
            ],
        ),
    ]
