# Generated by Django 3.2.23 on 2024-04-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0013_auto_20240403_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurritemslist',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
