# Generated by Django 3.2.23 on 2024-04-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0014_alter_recurritemslist_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurring_bills',
            old_name='ajustment',
            new_name='adjustment',
        ),
    ]
