# Generated by Django 3.2.23 on 2024-02-27 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
        ('Company_Staff', '0014_commentsalarydetails_historysalarydetails_salarydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loandate', models.DateField(null=True)),
                ('LoanAmount', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=255)),
                ('Expiry_date', models.DateField(null=True)),
                ('payment_method', models.CharField(blank=True, max_length=220, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=220, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=220, null=True)),
                ('bank_acc_number', models.CharField(blank=True, max_length=220, null=True)),
                ('Monthly_payment_type', models.CharField(blank=True, max_length=220, null=True)),
                ('MonthlyCut_percentage', models.IntegerField(blank=True, null=True)),
                ('MonthlyCut_Amount', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=220, null=True)),
                ('file', models.FileField(null=True, upload_to='images/')),
                ('status', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('emp_name', models.CharField(blank=True, max_length=220, null=True)),
                ('emp_no', models.IntegerField(blank=True, null=True)),
                ('join_date', models.DateField(null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.payroll_employee')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='LoanDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(choices=[('Months', 'Months'), ('Month', 'Month'), ('Years', 'Years'), ('Year', 'Year')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('logindetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.IntegerField(null=True)),
                ('interest_amonut', models.IntegerField(null=True)),
                ('payment_date', models.DateField(null=True)),
                ('payment_method', models.CharField(max_length=255, null=True)),
                ('cheque_id', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total_payment', models.IntegerField(null=True)),
                ('balance', models.IntegerField(null=True)),
                ('particular', models.CharField(max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.employeeloan')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.payroll_employee')),
                ('logindetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='Employeeloan_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True, null=True)),
                ('action', models.CharField(blank=True, max_length=220, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('employeeloan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.employeeloan')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='employeeloan_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.employeeloan')),
                ('logindetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
    ]
