# Generated by Django 3.2.23 on 2024-02-28 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
        ('Company_Staff', '0015_employeeloan_employeeloan_comments_employeeloan_history_employeeloanrepayment_loanduration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(blank=True, max_length=220, null=True)),
                ('title', models.CharField(blank=True, max_length=220, null=True)),
                ('first_name', models.CharField(blank=True, max_length=220, null=True)),
                ('last_name', models.CharField(blank=True, max_length=220, null=True)),
                ('customer_display_name', models.CharField(blank=True, max_length=220, null=True)),
                ('company_name', models.CharField(blank=True, max_length=220, null=True)),
                ('customer_email', models.EmailField(max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=220, null=True)),
                ('customer_mobile', models.CharField(blank=True, max_length=220, null=True)),
                ('skype', models.CharField(blank=True, max_length=220, null=True)),
                ('designation', models.CharField(blank=True, max_length=220, null=True)),
                ('department', models.CharField(blank=True, max_length=220, null=True)),
                ('website', models.CharField(blank=True, max_length=220, null=True)),
                ('GST_treatement', models.CharField(blank=True, max_length=220, null=True)),
                ('GST_number', models.CharField(blank=True, max_length=220, null=True)),
                ('PAN_number', models.CharField(blank=True, max_length=220, null=True)),
                ('place_of_supply', models.CharField(blank=True, max_length=220, null=True)),
                ('tax_preference', models.CharField(blank=True, max_length=220, null=True)),
                ('currency', models.CharField(blank=True, max_length=220, null=True)),
                ('opening_balance_type', models.CharField(blank=True, max_length=220, null=True)),
                ('opening_balance', models.FloatField(blank=True, default=0.0, null=True)),
                ('credit_limit', models.FloatField(blank=True, null=True)),
                ('price_list', models.CharField(blank=True, max_length=220, null=True)),
                ('portal_language', models.CharField(blank=True, max_length=220, null=True)),
                ('facebook', models.CharField(blank=True, max_length=220, null=True)),
                ('twitter', models.CharField(blank=True, max_length=220, null=True)),
                ('current_balance', models.FloatField(blank=True, default=0.0, null=True)),
                ('billing_attention', models.CharField(blank=True, max_length=220, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=220, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=220, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=220, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=220, null=True)),
                ('billing_pincode', models.CharField(blank=True, max_length=220, null=True)),
                ('billing_mobile', models.CharField(blank=True, max_length=220, null=True)),
                ('billing_fax', models.CharField(blank=True, max_length=220, null=True)),
                ('shipping_attention', models.CharField(blank=True, max_length=220, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=220, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=220, null=True)),
                ('shipping_state', models.CharField(blank=True, max_length=220, null=True)),
                ('shipping_country', models.CharField(blank=True, max_length=220, null=True)),
                ('shipping_pincode', models.CharField(blank=True, max_length=220, null=True)),
                ('shipping_mobile', models.CharField(blank=True, max_length=220, null=True)),
                ('shipping_fax', models.CharField(blank=True, max_length=220, null=True)),
                ('remarks', models.CharField(blank=True, max_length=220, null=True)),
                ('customer_status', models.CharField(blank=True, max_length=220, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('company_payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.company_payment_term')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_remarks_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_doc_upload_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('document', models.FileField(upload_to='doc/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.customer')),
                ('login_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_comments_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.customer')),
                ('login_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
    ]
