# Generated by Django 3.2.23 on 2024-04-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0017_remove_recurr_history_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurring_bills',
            old_name='check_no',
            new_name='cheque_no',
        ),
    ]
