# Generated by Django 3.2.23 on 2024-03-02 06:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
        ('Company_Staff', '0017_customercontactpersons_customerhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('account_type', models.CharField(max_length=2)),
                ('bankname', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=15, unique=True)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('swift_code', models.CharField(max_length=11)),
                ('branch_name', models.CharField(max_length=100)),
                ('cheque_book_range', models.CharField(max_length=5)),
                ('enable_cheque_printing', models.CharField(max_length=3)),
                ('cheque_printing_configuration', models.CharField(max_length=3)),
                ('mailing_name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('pin', models.CharField(max_length=6)),
                ('pan_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('registration_type', models.CharField(max_length=15)),
                ('gst_num', models.CharField(blank=True, max_length=15)),
                ('alter_gst_details', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('amount_type', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.banking')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='loan_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=15, null=True, unique=True)),
                ('loan_amount', models.IntegerField()),
                ('balance', models.IntegerField(default=0, null=True)),
                ('lender_bank', models.CharField(max_length=255)),
                ('loan_date', models.DateField()),
                ('payment_method', models.CharField(max_length=255)),
                ('upi_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cheque', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('payment_accountnumber', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('processing_method', models.CharField(max_length=255)),
                ('processing_upi', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('processing_cheque', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('processing_acc', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('processing_fee', models.IntegerField(blank=True, default='', null=True)),
                ('term', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('interest', models.IntegerField(blank=True, default='', null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.TextField(default='Active')),
                ('bank_holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.bankaccount')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayemnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.IntegerField(blank=True, null=True)),
                ('interest_amount', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(max_length=255)),
                ('upi_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('cheque', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.loan_account')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('action', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
                ('repayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.loanrepayemnt')),
            ],
        ),
        migrations.CreateModel(
            name='LoanAccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('action', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.loan_account')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('term', models.CharField(blank=True, max_length=255, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
            ],
        ),
        migrations.AddField(
            model_name='loan_account',
            name='loan_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.loan_term'),
        ),
        migrations.AddField(
            model_name='loan_account',
            name='logindetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.loan_account')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(max_length=10)),
                ('bank_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.bankaccount')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('logindetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
    ]
