# Generated by Django 3.2.23 on 2024-03-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0019_godown_godowncomments_godownhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='status',
            field=models.CharField(default='Active', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='alias',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='alter_gst_details',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='amount_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bankname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='branch_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='cheque_book_range',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='cheque_printing_configuration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='customer_name',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='enable_cheque_printing',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='gst_num',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='ifsc_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='mailing_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='pan_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='pin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='registration_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='swift_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccounthistory',
            name='action',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccounthistory',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
