# Generated by Django 3.2.23 on 2024-04-07 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0021_auto_20240405_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='recurr_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('recurr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.recurring_bills')),
            ],
        ),
    ]
