# Generated by Django 3.2.23 on 2024-04-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0022_recurr_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_bills',
            name='template1_doc',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
    ]
