# Generated by Django 3.2.25 on 2024-03-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0023_invoice_invoicecomments_invoicehistory_invoiceitems_invoicereference'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalrecievedidmodel',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
