# Generated by Django 3.2.23 on 2024-04-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0023_recurring_bills_template1_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurritemslist',
            name='bal_qty',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
