# Generated by Django 3.2.23 on 2024-04-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0024_recurritemslist_bal_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurritemslist',
            name='total_qty',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
