# Generated by Django 3.2.23 on 2024-04-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0025_recurritemslist_total_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurritemslist',
            name='bal_qty',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recurritemslist',
            name='qty',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recurritemslist',
            name='total_qty',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
