# Generated by Django 3.2.23 on 2024-04-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0026_auto_20240408_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_bills',
            name='bank_acc_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recurring_bills',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
