# Generated by Django 3.2.23 on 2024-04-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0027_auto_20240409_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_bills',
            name='price_list_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
